const RandomClusteredMaps = () => ([
  'distractor-clustered-large_smooth-distractor-color-mixed_v1-basemap-none',
  'distractor-clustered-medium_smooth-distractor-color-mixed_v1-basemap-none',
  'distractor-clustered-small_smooth-distractor-color-mixed_v1-basemap-none',
  'distractor-clustered--large_rough-distractor-color-mixed_v1-basemap-none',
  'distractor-clustered-medium_rough-distractor-color-mixed_v1-basemap-none',
  'distractor-clustered-small_rough-distractor-color-mixed_v1-basemap-none',
  // 'distractor-clustered-medium_smooth-distractor-color-matches_target-basemap-none',
  // 'distractor-clustered-small_smooth-distractor-color-matches_target-basemap-none',
  // 'distractor-clustered--large_rough-distractor-color-matches_target-basemap-none',
  // 'distractor-clustered-medium_rough-distractor-color-matches_target-basemap-none',
  // 'distractor-clustered-small_rough-distractor-color-matches_target-basemap-none',
  // 'distractor-clustered-large_smooth-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered-medium_smooth-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered-small_smooth-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered--large_rough-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered-medium_rough-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered-small_rough-distractor-color-matches_target-basemap-streets',
  // 'distractor-clustered-large_smooth-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered-medium_smooth-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered-small_smooth-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered--large_rough-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered-medium_rough-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered-small_rough-distractor-color-matches_target-basemap-dark',
  // 'distractor-clustered-large_smooth-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered-medium_smooth-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered-small_smooth-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered--large_rough-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered-medium_rough-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered-small_rough-distractor-color-matches_target-basemap-imagery',
  // 'distractor-clustered-large_smooth-distractor-color-red-basemap-none',
  // 'distractor-clustered-medium_smooth-distractor-color-red-basemap-none',
  // 'distractor-clustered-small_smooth-distractor-color-red-basemap-none',
  // 'distractor-clustered--large_rough-distractor-color-red-basemap-none',
  // 'distractor-clustered-medium_rough-distractor-color-red-basemap-none',
  // 'distractor-clustered-small_rough-distractor-color-red-basemap-none',
  // 'distractor-clustered-large_smooth-distractor-color-red-basemap-streets',
  // 'distractor-clustered-medium_smooth-distractor-color-red-basemap-streets',
  // 'distractor-clustered-small_smooth-distractor-color-red-basemap-streets',
  // 'distractor-clustered--large_rough-distractor-color-red-basemap-streets',
  // 'distractor-clustered-medium_rough-distractor-color-red-basemap-streets',
  // 'distractor-clustered-small_rough-distractor-color-red-basemap-streets',
  // 'distractor-clustered-large_smooth-distractor-color-red-basemap-dark',
  // 'distractor-clustered-medium_smooth-distractor-color-red-basemap-dark',
  // 'distractor-clustered-small_smooth-distractor-color-red-basemap-dark',
  // 'distractor-clustered--large_rough-distractor-color-red-basemap-dark',
  // 'distractor-clustered-medium_rough-distractor-color-red-basemap-dark',
  // 'distractor-clustered-small_rough-distractor-color-red-basemap-dark',
  // 'distractor-clustered-large_smooth-distractor-color-red-basemap-imagery',
  // 'distractor-clustered-medium_smooth-distractor-color-red-basemap-imagery',
  // 'distractor-clustered-small_smooth-distractor-color-red-basemap-imagery',
  // 'distractor-clustered--large_rough-distractor-color-red-basemap-imagery',
  // 'distractor-clustered-medium_rough-distractor-color-red-basemap-imagery',
  // 'distractor-clustered-small_rough-distractor-color-red-basemap-imagery',
  // 'distractor-clustered-large_smooth-distractor-color-blue-basemap-none',
  // 'distractor-clustered-medium_smooth-distractor-color-blue-basemap-none',
  // 'distractor-clustered-small_smooth-distractor-color-blue-basemap-none',
  // 'distractor-clustered--large_rough-distractor-color-blue-basemap-none',
  // 'distractor-clustered-medium_rough-distractor-color-blue-basemap-none',
  // 'distractor-clustered-small_rough-distractor-color-blue-basemap-none',
  // 'distractor-clustered-large_smooth-distractor-color-blue-basemap-streets',
  // 'distractor-clustered-medium_smooth-distractor-color-blue-basemap-streets',
  // 'distractor-clustered-small_smooth-distractor-color-blue-basemap-streets',
  // 'distractor-clustered--large_rough-distractor-color-blue-basemap-streets',
  // 'distractor-clustered-medium_rough-distractor-color-blue-basemap-streets',
  // 'distractor-clustered-small_rough-distractor-color-blue-basemap-streets',
  // 'distractor-clustered-large_smooth-distractor-color-blue-basemap-dark',
  // 'distractor-clustered-medium_smooth-distractor-color-blue-basemap-dark',
  // 'distractor-clustered-small_smooth-distractor-color-blue-basemap-dark',
  // 'distractor-clustered--large_rough-distractor-color-blue-basemap-dark',
  // 'distractor-clustered-medium_rough-distractor-color-blue-basemap-dark',
  // 'distractor-clustered-small_rough-distractor-color-blue-basemap-dark',
  // 'distractor-clustered-large_smooth-distractor-color-blue-basemap-imagery',
  // 'distractor-clustered-medium_smooth-distractor-color-blue-basemap-imagery',
  // 'distractor-clustered-small_smooth-distractor-color-blue-basemap-imagery',
  // 'distractor-clustered--large_rough-distractor-color-blue-basemap-imagery',
  // 'distractor-clustered-medium_rough-distractor-color-blue-basemap-imagery',
  // 'distractor-clustered-small_rough-distractor-color-blue-basemap-imagery'
]);

export default RandomClusteredMaps;
